Algoritmo "Area e perimetro do quadrado "
// LPA 
// Liliane Balduino 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo Leandro
// Data atual  : 2/9/19
Var

area,lado,perimetro : real


Inicio

escreval("Entre com o lado do quadrado: ")
leia(lado)

area <- lado^2
perimetro <- 4* lado

escreval("Área:", area)
escreval("Perímetro:",perimetro)


Fimalgoritmo