Algoritmo "Aumento"
// LPA 
// Liliane Balduino 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo Leandro da Silva Lima
// Data atual  : 2/9/19
Var

 salario,aumento :real

Inicio

escreva("Entre com o sálario:")
leia(salario)

aumento <- salario * (18/100)
salario <- salario + aumento

escreval("O novo sálario é de:",salario)


Fimalgoritmo