Algoritmo "Gasto de combustivel"
// LPA 
// Liliane Balduino 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo Leandro
// Data atual  : 2/9/19
Var

temp,velo,dist, comb :real

Inicio

escreva("Tempo gasto: ")
leia(temp)

escreva("velocidade média: ")
leia(velo)

dist <- temp*velo

comb <- dist/13

escreval("Quantidade de combustivel gasto: " , comb)

Fimalgoritmo