Algoritmo "Idade"
// LPA 
// Liliane Balduino 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo Leandro
// Data atual  : 2/9/19
Var

 nasc,idade,idade46,ano :real

Inicio

escreval("Ano atual:")
 leia(ano)

escreval("Qual seu ano de nascimento: ")
 leia(nasc)
 
idade <- ano-nasc

idade46 <- 2046-nasc

escreval("Idade atual é ", idade)
escreval("Idade em 2046 é ", idade46)
 




Fimalgoritmo