Algoritmo "Troca de posição"
// LPA 
// Liliane Balduino 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Rodrigo Leandro da Silva Lima
// Data atual  : 2/9/19
Var

   a, b, c :real


Inicio

escreval("Entre com um numero: ")
 leia(a)
escreval("Entre com o segundo numero: ")
 leia(b)
 
 c <- a
 a<- b
 b <- c
 
 escreval("Váriavel A", a)
 escreval("Variavel B", b)

Fimalgoritmo